### ISSUE TITLE
(Space Joker) Indicate the hand it has a chance to upgrade and show the odds in green bracketed text

### ISSUE THREAD

**Issue by OppositeWolf770** [nh6574/JokerDisplay#14]
I've got a working version of this that needs polishing if this is something that seems like a good addition.

**Comment by nh6574** [comment]
I think having the odds is a good idea for consistency reasons.

I didn't add the poker hand because I felt it was a bit redundant when it's already displayed on the left UI. Same with Burnt Joker. Adding too much text on jokers leads to too much clutter on screen and this info is already there. I'm open to discussion though.

**Comment by OppositeWolf770** [comment]
I actually agree with you. My initial thought was it would be nice to have all the info in one place, but it _is_ a little redundant. Probably just showing the odds is the best way to implement it.
