### ISSUE TITLE
(Misprint) Make it display effective Mult when hand played

### ISSUE THREAD

**Issue by OppositeWolf770** [nh6574/JokerDisplay#21]
I don't know if this is even possible, but it might be more informative for the Misprint Joker to display the actual Mult that will be applied to the current played hand once you submit a hand.

So basically display random values normally, and then as soon as you hit play hand it displays the appropriate value. This might not be necessary, but it's something to think about

**Comment by nh6574** [comment]
I'm pretty sure this isn't possible because the number is calculated the moment it is applied. I will look into it *but* if I add it it will be as an optional thing as the idea of this mod is to complement the vanilla experience not give you information you wouldn't know otherwise.

Maybe the range (+0 to +23) as a reminder could be useful? Though it would kind of ruin the charm of it.

**Comment by OppositeWolf770** [comment]
> it will be as an optional thing as the idea of this mod is to complement the vanilla experience not give you information you wouldn't know otherwise.

That's true. But my thought was at that point there's nothing you can do to change the output, so having the information wouldn't influence your decision-making. But I understand where you're coming from.

And yeah, having a config in-game would be awesome. If that's even possible in the current state of Steamodded.

**Comment by nh6574** [comment]
Oh, wait. I reread that and I saw you meant only when playing a hand, sorry. I'm still sure it's not possible.

**Comment by OppositeWolf770** [comment]
Honestly, now that I am thinking about it, this change really isn't necessary. You would only be able to see it for a short time, and the game tells you how much it gives you anyway.
